spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/L4Y4EVER/config-repository.git
          username: L4Y4EVER
          password: lhy521987
          basedir: E:/coder/coderSelf/code/config/basedir


eureka:
  client:
    service-url:
<<<<<<< HEAD
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/
=======
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
# 这里是将所有的接口路径暴露出来，我竟然天真的以为是给密码加密的，我的天哪。
>>>>>>> 3b5261f8ad82fe2c9318677bf56f1457c71e34cc
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
#    jmx:
#      exposure:
#        include: "*"
