spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://git.imooc.com/springcloudtest/config-repo.git
          username: L4Y4EVER
          password: lhy521987
          basedir: C:/Java/coder/config/basedir

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
management:
  endpoints:
    web:
      expose: "*"