spring:
  profiles:
    active: eureka1
management:
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"
    health:
      show-details: always
# spring cloud access&secret config
# 可以访问如下地址查看: https://usercenter.console.aliyun.com/#/manage/ak
#alibaba.cloud.access-key=****
#alibaba.cloud.secret-key=****


